/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tes.database;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class formKoneksi extends javax.swing.JFrame {
    private static Connection koneksi;
    private DefaultTableModel model;

    /**
     * Creates new form formKoneksi
     */
    public formKoneksi() {
        initComponents();
        model = new DefaultTableModel();
        Table1.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        ambilDataTable();
    }

    private static Connection bukaKoneksi() {
        if (koneksi == null) {
            try {
                String url = "jdbc:mysql://localhost:3306/javadb";
                String user = "root";
                String password = "";
                
                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi = DriverManager.getConnection(url, user, password);
            }catch(SQLException e) {
                System.out.println("error membuat koneksi");
            }        
            }
        return koneksi;
      
    }
    
    private void ambilDataTable() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = bukaKoneksi();
            Statement s = c.createStatement();
            String sql =  "SELECT * from anggota";
            ResultSet r = s.executeQuery (sql);
            
            while (r.next ()) {
                Object[] o= new Object[4];
                o[0]=r.getString("id");
                o[1]=r.getString("nama");
                o[2]=r.getString("alamat");
                o[3]=r.getString("telp");
                model.addRow(o);
            }
            r.close();
            s.close();
            ambilTableKlik();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan"+e.getMessage());
        }
        
    }
    private void ambilTableKlik() {
        int i = Table1.getSelectedRow();
        if (i == -1) {
            return;
        }
    String kode = (String) model.getValueAt(i, 0);
    kodeLabel.setText(kode);
    String nama = (String) model.getValueAt(i, 1);
    NamaInput.setText(nama);
    String alamat = (String) model.getValueAt(i, 2);
    AlamatInput.setText(alamat);
    String telp = (String) model.getValueAt (i, 3);
    
    AddBtn.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NamaInput = new javax.swing.JTextField();
        AlamatInput = new javax.swing.JTextField();
        TelpInput = new javax.swing.JTextField();
        kodeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        RefreshBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        jLabel3.setText("Telepon");

        NamaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaInputActionPerformed(evt);
            }
        });

        kodeLabel.setText("0");

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        RefreshBtn.setText("Refresh");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelpInput)
                            .addComponent(NamaInput)
                            .addComponent(AlamatInput))
                        .addGap(18, 18, 18)
                        .addComponent(kodeLabel)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(118, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddBtn)
                        .addGap(44, 44, 44)
                        .addComponent(EditBtn)
                        .addGap(36, 36, 36)
                        .addComponent(DeleteBtn)
                        .addGap(37, 37, 37)
                        .addComponent(RefreshBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AlamatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TelpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn)
                    .addComponent(EditBtn)
                    .addComponent(DeleteBtn)
                    .addComponent(RefreshBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaInputActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        Connection c=bukaKoneksi();
        if("Add".equals(AddBtn.getText()))
        {
            AddBtn.setText("Save");
            EditBtn.setText("Cancel");
            DeleteBtn.setEnabled(false);
            RefreshBtn.setEnabled(false);
        }else if ("Save".equals(AddBtn.getText()))
        {    
        
         String sqlkode="Insert into anggota (nama,alamat,telp) values"
                    + "('" + NamaInput.getText()+"',"
                    + "'" + AlamatInput.getText()+"',"
                    + "'" + TelpInput.getText()+"')";
        try{
            PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
            p2.executeUpdate();
            p2.close();
            
            kodeLabel.setText("0");
            NamaInput.setText("");
            AlamatInput.setText("");
            TelpInput.setText("");
            AddBtn.setEnabled (true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Terjadi kesalahan"+e.getMessage());
        }
        AddBtn.setText("Add");
        EditBtn.setText("Edit");
        DeleteBtn.setEnabled(true);
        RefreshBtn.setEnabled(true);
        }else if ("Update".equals(AddBtn.getText())){
            String sqlkode="Update anggota SET nama='"+NamaInput.getText()+"',"
            + "Alamat='"+AlamatInput.getText()+"'"
            + "where ID='"+kodeLabel.getText()+"'";
    try {
        PreparedStatement p2=(PreparedStatement)
        c.prepareStatement (sqlkode);
        p2.executeUpdate();
        p2.close();
        
        kodeLabel.setText("0");
        NamaInput.setText("");
        AlamatInput.setText("");
        TelpInput.setText("");
        AddBtn.setEnabled(true);
    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan"+e.getMessage());
   }
   AddBtn.setText("Add");
   EditBtn.setText("Edit");
   DeleteBtn.setEnabled(true);
   RefreshBtn.setEnabled(true);
        }      
    }//GEN-LAST:event_AddBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        if("Edit".equals(EditBtn.getText())) {
            AddBtn.setText("Update");
            EditBtn.setText("Cancel");
            DeleteBtn.setEnabled(true);
            RefreshBtn.setEnabled(true);
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        Connection c = bukaKoneksi();
        String sqlkode = "DELETE FROM anggota WHERE id = " + kodeLabel.getText()+ ";";
        try {
            PreparedStatement p2=(PreparedStatement)
            c.prepareStatement (sqlkode);
            p2.executeUpdate();
            p2.close();
            
            kodeLabel.setText("0");
            NamaInput.setText("");
            AlamatInput.setText("");
            TelpInput.setText("");
            AddBtn.setEnabled(true);
          } catch (SQLException e) {
              JOptionPane.showMessageDialog(this, "Terjadi kesalahan"+e.getMessage());
          }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
        ambilDataTable();
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        ambilTableKlik();
    }//GEN-LAST:event_Table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKoneksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField AlamatInput;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField NamaInput;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JTable Table1;
    private javax.swing.JTextField TelpInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kodeLabel;
    // End of variables declaration//GEN-END:variables
}
